derivatives:
  order: 2
  
domain:
  start: -1.0
  end: 1.0
  points: 21

time:
  last-iter: 1
  courant-factor: 0.5

initial-data:
  type: "standing-wave"
  standing-wave:
    A: 1.0
    Kx: 1.0
    Ky: 1.0
    Kz: 1.0

RKAB:
  c1: 1.0
  c2: 1.0
  c3: 1.0
  c4: 1.0
  c5: 1.0
  c6: 1.0
  c7: 1.0
  c8: 1.0
